import json

file_path = 'notebooks/07_Evaluation.ipynb'

with open(file_path, 'r', encoding='utf-8') as f:
    nb = json.load(f)

for cell in nb.get('cells', []):
    if cell.get('cell_type') != 'code':
        continue
    
    new_source = []
    for line in cell.get('source', []):
        line = line.replace("rec_list = global_top20[:5]", "rec_list = global_top20[:10]")
        line = line.replace("rec_list = combined[:5]", "rec_list = combined[:10]")
        line = line.replace("if len(rec_list) < 5:", "if len(rec_list) < 10:")
        line = line.replace("if len(rec_list) == 5:", "if len(rec_list) == 10:")
        line = line.replace("top5_idx = np.argsort(preds[0])[-5:][::-1]", "top10_idx = np.argsort(preds[0])[-10:][::-1]")
        line = line.replace("rec_list = [int(x) for x in top5_idx]", "rec_list = [int(x) for x in top10_idx]")
        
        # also update 07_Evaluation.ipynb full system HR@10 calculation comment if it's there
        line = line.replace("'HR@10': hit_rate(y_true, preds_full, 10), # Only 5 generated by router, but compute anyway",
                            "'HR@10': hit_rate(y_true, preds_full, 10),")
        
        new_source.append(line)
        
    cell['source'] = new_source

with open(file_path, 'w', encoding='utf-8') as f:
    json.dump(nb, f, indent=2)

print("Notebook router limit fixed from 5 to 10.")
