export const getFoodEmoji = (productName = '') => {
  const n = productName.toLowerCase();
  if (n.includes('banana')) return '🍌';
  if (n.includes('strawberr')) return '🍓';
  if (n.includes('blueberr') || n.includes('blackberr')) return '🫐';
  if (n.includes('raspberr')) return '🍓';
  if (n.includes('apple')) return '🍎';
  if (n.includes('orange')) return '🍊';
  if (n.includes('lemon') || n.includes('lime')) return '🍋';
  if (n.includes('grape')) return '🍇';
  if (n.includes('mango')) return '🥭';
  if (n.includes('peach') || n.includes('nectarine') || n.includes('plum')) return '🍑';
  if (n.includes('cherry') || n.includes('cherri')) return '🍒';
  if (n.includes('watermelon')) return '🍉';
  if (n.includes('pineapple')) return '🍍';
  if (n.includes('coconut')) return '🥥';
  if (n.includes('kiwi')) return '🥝';
  if (n.includes('pear')) return '🍐';
  if (n.includes('cantaloupe') || n.includes('honeydew') || n.includes('melon')) return '🍈';
  if (n.includes('fig') || n.includes('pomegranate') || n.includes('berry') || n.includes('berries')) return '🫐';
  if (n.includes('avocado')) return '🥑';
  if (n.includes('tomato')) return '🍅';
  if (n.includes('carrot')) return '🥕';
  if (n.includes('broccoli') || n.includes('cauliflower') || n.includes('brussels') || n.includes('cabbage') || n.includes('asparagus')) return '🥦';
  if (n.includes('spinach') || n.includes('kale') || n.includes('arugula') || n.includes('chard') || n.includes('lettuce') || n.includes('mixed green') || n.includes('salad green') || n.includes('herb') || n.includes('cilantro') || n.includes('parsley') || n.includes('basil') || n.includes('mint') || n.includes('thyme') || n.includes('dill')) return '🥬';
  if (n.includes('corn')) return '🌽';
  if (n.includes('pepper')) return '🫑';
  if (n.includes('cucumber')) return '🥒';
  if (n.includes('eggplant') || n.includes('aubergine')) return '🍆';
  if (n.includes('mushroom')) return '🍄';
  if (n.includes('garlic')) return '🧄';
  if (n.includes('onion') || n.includes('scallion') || n.includes('leek') || n.includes('shallot')) return '🧅';
  if (n.includes('sweet potato') || n.includes('yam')) return '🍠';
  if (n.includes('potato')) return '🥔';
  if (n.includes('zucchini') || n.includes('squash') || n.includes('pumpkin')) return '🎃';
  if (n.includes('ginger') || n.includes('turmeric') || n.includes('beet') || n.includes('radish') || n.includes('turnip')) return '🥕';
  if (n.includes('milk')) return '🥛';
  if (n.includes('cheese')) return '🧀';
  if (n.includes('egg')) return '🥚';
  if (n.includes('butter')) return '🧈';
  if (n.includes('yogurt') || n.includes('yoghurt') || n.includes('kefir')) return '🥛';
  if (n.includes('cream') || n.includes('creamer')) return '🥛';
  if (n.includes('bagel')) return '🥯';
  if (n.includes('bread') || n.includes('baguette') || n.includes('loaf') || n.includes('roll')) return '🍞';
  if (n.includes('muffin') || n.includes('cupcake')) return '🧁';
  if (n.includes('croissant') || n.includes('pastry') || n.includes('cake')) return '🥐';
  if (n.includes('cookie') || n.includes('biscuit') || n.includes('cracker')) return '🍪';
  if (n.includes('tortilla') || n.includes('wrap') || n.includes('pita')) return '🫓';
  if (n.includes('coffee') || n.includes('espresso') || n.includes('latte')) return '☕';
  if (n.includes('tea')) return '🍵';
  if (n.includes('juice')) return '🧃';
  if (n.includes('water') && !n.includes('watermelon')) return '💧';
  if (n.includes('soda') || n.includes('sparkling') || n.includes('cola') || n.includes('energy drink')) return '🥤';
  if (n.includes('beer') || n.includes('ale') || n.includes('lager')) return '🍺';
  if (n.includes('wine')) return '🍷';
  if (n.includes('kombucha')) return '🧃';
  if (n.includes('chicken') || n.includes('turkey') || n.includes('poultry')) return '🍗';
  if (n.includes('beef') || n.includes('steak') || n.includes('ground')) return '🥩';
  if (n.includes('bacon') || n.includes('ham') || n.includes('pork') || n.includes('sausage')) return '🥓';
  if (n.includes('salmon') || n.includes('tuna') || n.includes('cod') || n.includes('fish') || n.includes('tilapia')) return '🐟';
  if (n.includes('shrimp') || n.includes('prawn') || n.includes('lobster') || n.includes('crab')) return '🦐';
  if (n.includes('pasta') || n.includes('spaghetti') || n.includes('penne') || n.includes('noodle') || n.includes('linguine')) return '🍝';
  if (n.includes('rice') || n.includes('quinoa') || n.includes('couscous') || n.includes('grain')) return '🍚';
  if (n.includes('bean') || n.includes('lentil') || n.includes('chickpea') || n.includes('legume')) return '🫘';
  if (n.includes('cereal') || n.includes('granola') || n.includes('oat') || n.includes('muesli')) return '🥣';
  if (n.includes('chip') || n.includes('crisp') || n.includes('pretzel')) return '🍟';
  if (n.includes('popcorn')) return '🍿';
  if (n.includes('chocolate') || n.includes('cocoa')) return '🍫';
  if (n.includes('candy') || n.includes('gummy')) return '🍬';
  if (n.includes('ice cream') || n.includes('sorbet')) return '🍦';
  if (n.includes('nut') || n.includes('almond') || n.includes('cashew') || n.includes('walnut') || n.includes('peanut') || n.includes('pistachio')) return '🥜';
  if (n.includes('oil')) return '🫙';
  if (n.includes('honey') || n.includes('maple syrup')) return '🍯';
  if (n.includes('sauce') || n.includes('ketchup') || n.includes('mustard') || n.includes('mayo') || n.includes('salsa') || n.includes('vinegar') || n.includes('dressing')) return '🫙';
  if (n.includes('salt') || n.includes('spice') || n.includes('seasoning')) return '🧂';
  if (n.includes('soup') || n.includes('broth') || n.includes('stock')) return '🍲';
  if (n.includes('frozen')) return '❄️';
  if (n.includes('organic') || n.includes('natural')) return '🌱';
  return '🛒';
};

export const getDeptStyle = (department = '') => {
  const dept = department.toLowerCase();
  if (dept.includes('produce')) return { iconBg: 'bg-green-100', iconText: 'text-green-600', badge: 'bg-green-50 text-green-700 border-green-200' };
  if (dept.includes('dairy') || dept.includes('egg')) return { iconBg: 'bg-blue-100', iconText: 'text-blue-600', badge: 'bg-blue-50 text-blue-700 border-blue-200' };
  if (dept.includes('meat') || dept.includes('seafood') || dept.includes('deli')) return { iconBg: 'bg-red-100', iconText: 'text-red-600', badge: 'bg-red-50 text-red-700 border-red-200' };
  if (dept.includes('bakery') || dept.includes('bread')) return { iconBg: 'bg-yellow-100', iconText: 'text-yellow-600', badge: 'bg-yellow-50 text-yellow-700 border-yellow-200' };
  if (dept.includes('snack') || dept.includes('cereal') || dept.includes('breakfast')) return { iconBg: 'bg-orange-100', iconText: 'text-orange-600', badge: 'bg-orange-50 text-orange-700 border-orange-200' };
  if (dept.includes('beverage') || dept.includes('drink') || dept.includes('water')) return { iconBg: 'bg-cyan-100', iconText: 'text-cyan-600', badge: 'bg-cyan-50 text-cyan-700 border-cyan-200' };
  if (dept.includes('frozen')) return { iconBg: 'bg-indigo-100', iconText: 'text-indigo-600', badge: 'bg-indigo-50 text-indigo-700 border-indigo-200' };
  if (dept.includes('pantry') || dept.includes('canned') || dept.includes('pasta') || dept.includes('spice') || dept.includes('dry')) return { iconBg: 'bg-amber-100', iconText: 'text-amber-600', badge: 'bg-amber-50 text-amber-700 border-amber-200' };
  if (dept.includes('personal') || dept.includes('health') || dept.includes('beauty')) return { iconBg: 'bg-pink-100', iconText: 'text-pink-600', badge: 'bg-pink-50 text-pink-700 border-pink-200' };
  if (dept.includes('household') || dept.includes('cleaning') || dept.includes('laundry')) return { iconBg: 'bg-purple-100', iconText: 'text-purple-600', badge: 'bg-purple-50 text-purple-700 border-purple-200' };
  return { iconBg: 'bg-emerald-100', iconText: 'text-emerald-600', badge: 'bg-emerald-50 text-emerald-700 border-emerald-200' };
};

export const getMockPrice = (productId) => {
  const seed = productId % 100;
  if (seed < 20) return (1.99 + (seed % 5) * 0.5).toFixed(2);
  if (seed < 50) return (2.49 + (seed % 8) * 0.25).toFixed(2);
  if (seed < 80) return (3.99 + (seed % 6) * 0.5).toFixed(2);
  return (4.99 + (seed % 10) * 0.3).toFixed(2);
};
